package IntDiffCalculator.app.src.main.java.IntDiffCalculator;

import java.util.List;

import IntDiffCalculator.app.src.main.java.IntDiffCalculator.AST.Expr.Expr;
/**
* Parser that is responsible for parsing a list of tokens generated by the lexer.
* <p>
* It handles precedence levels and associativity of operators, and produces an AST representation of the expression.
* </p>
* <p>
* Precedence:
* - Parentheses
* - Functions (e.g. sin, cos, ln)
* - Numbers/Variables
* - Unary operators (e.g. negation)
* - Binary operators (e.g. +, -, *, /). ^, * and /, then + and -. In that order is the precedence of binary ops.
* Associativity:
* - left associativity for binary operators (e.g. 1 - 2 - 3 is parsed as (1 - 2) - 3)
* </p>
*/
public class Parser {
  private List<Token> tokens;
  private int pos = 0; // tracks position same as lexer
  
  /**
  * Parses a list of tokensinto an AST (Abstract Syntax Tree)
  * @param tokens the list of tokens to parse
  * @return Expr: an AST representation of the expression
  */
  public Expr parse(List<Token> tokens) {
    this.tokens = tokens;
    this.pos = 0;
    return parseExpr();
  }
  
  private Expr parseExpr() {
    // Handle + and -
    return parseTerm();
  }
  
  private Expr parseTerm() {
    // handle * and /
    return parsePower();
  }
  
  private Expr parsePower() {
    // handle ^
    return parseUnary();
  }
  
  private Expr parseUnary() {
    // handle unary operators and functions
    return parsePrimary();
  }
  
  private Expr parsePrimary() {
    // handle numbers, variables and parentheses
    return null;
  }
  
  private Token peek() {
    return tokens.get(pos);
  }
  
  /**
  * Returns and consumes the current token.
  * @return Token: the current token and then consumes by moving forward position.
  */
  private Token consume() {
    return tokens.get(pos++);
  }
  
  private Token expect(TokenType type) {
    Token token = peek();
    if (token.type() != type) {
      throw new IllegalArgumentException("Expected token of type " + type + " but got " + token.type());
    }
    return consume();
  }
}
