package IntDiffCalculator;

import java.util.List;

import IntDiffCalculator.AST.Expr.*;
import IntDiffCalculator.AST.Op.*;


/**
* Parser that is responsible for parsing a list of tokens generated by the lexer.
* <p>
* It handles precedence levels and associativity of operators, and produces an AST representation of the expression.
* </p>
* <p>
* Precedence:
* - Parentheses
* - Functions (e.g. sin, cos, ln)
* - Numbers/Variables
* - Unary operators (e.g. negation)
* - Binary operators (e.g. +, -, *, /). ^, * and /, then + and -. In that order is the precedence of binary ops.
* Associativity:
* - left associativity for binary operators (e.g. 1 - 2 - 3 is parsed as (1 - 2) - 3)
* </p>
*/
public class Parser {
  private List<Token> tokens;
  private int pos = 0; // tracks position same as lexer
  
  /**
  * Parses a list of tokensinto an AST (Abstract Syntax Tree)
  * @param tokens the list of tokens to parse
  * @return Expr: an AST representation of the expression
  */
  public Expr parse(List<Token> tokens) {
    this.tokens = tokens;
    this.pos = 0;
    return parseExpr();
  }
  
  /**
   * Parses expressions, which are terms connected by + and -.
   * <p>
   * Represented in the cfg as term (('+' | '-') term)*.
   * </p>
   * @return Expr: the parsed expression.
   */
  private Expr parseExpr() {
    // Handle + and -
    Expr left = parseTerm();

    // 0 or more, encoded by * in expression.
    while (peek().type() == TokenType.PLUS || peek().type() == TokenType.MINUS) {
      // Must start with either + or -

      BinaryOp operator = switch (peek().type()) {
        case TokenType.PLUS -> BinaryOp.ADD;
        case TokenType.MINUS -> BinaryOp.SUB;
        default -> throw new IllegalStateException("Unexpected token: " + peek() + ". Expected + or -");
      };
      consume();
      Expr right = parseTerm();
      left = new BinaryExpr(operator, left, right); // fold into left
    }
    return left;
  }
  
  /**
   * Parses terms, which are factors connected by * and /.
   * <p>
   * Represented in the cfg as power (('*' | '/') power)*.
   * </p>
   * @return Expr: the parsed term.
   */
  private Expr parseTerm() {
    // handle * and /
    Expr left = parsePower();
    
    // 0 or more, encoded by * in term.
    while (peek().type() == TokenType.STAR || peek().type() == TokenType.SLASH) {
      // Must start with either * or /

      BinaryOp operator = switch (peek().type()) {
        case TokenType.STAR -> BinaryOp.MUL;
        case TokenType.SLASH -> BinaryOp.DIV;
        default -> throw new IllegalStateException("Unexpected token: " + peek() + ". Expected * or /");
      };
      consume();
      Expr right = parsePower();
      left = new BinaryExpr(operator, left, right); // fold into left
    }
    return left;
  }
  
  /**
   * Parses exponential expressions. Handles right associativity of exponentiation. E.g. 2^3^4 is parsed as 2^(3^4).
   * <p>
   * Represented in the cfg as unary ('^' power)?.
   * </p>
   * @return Expr: the parsed exponential expression.
   */
  private Expr parsePower() {
    Expr left = parseUnary();

    if (peek().type() == TokenType.CARET) {
      consume(); // consume "^"
      Expr right = parsePower(); // recusive call to handle right associativity
      return new BinaryExpr(BinaryOp.POW, left, right);
    }

    return left;
  }
  
  /**
   * Parses unary expressions. Represented in the cfg as '-' unary | primary.
   * @return Expr: the parsed unary expression.
   */
  private Expr parseUnary() {
    if (peek().type() == TokenType.MINUS) {
      // parse '-' unary
      consumeExpected(TokenType.MINUS); // consume "-"
      Expr operand = parseUnary(); // recursive call to handle multiple unary operators, e.g. --x
      return new UnaryExpr(UnaryOp.NEG, operand);
    } 

    // else primary
    return parsePrimary();
  }
  
  /**
   * Parses primary expressions: numbers, variables, and parentheses.
   * Represented in the cfg as NUMBER | IDENTIFIER | IDENTIFIER '(' expression ')' | '(' expression ')'.
   * <p>
   * Also handles mathematical constants, such as pi and e.
   * </p>
   * @return Expr: the parsed expression of the current token.
   * @throws IllegalArgumentException if the token has an unknown type.
   */
  private Expr parsePrimary() {
    Token token = peek();

    return switch (token.type()) {
      case NUMBER -> {
        Token numberToken = consumeExpected(TokenType.NUMBER); // consume number
        yield new NumberExpr(Double.parseDouble(numberToken.value()));
      }
      case IDENTIFIER -> {
        Token identToken = consumeExpected(TokenType.IDENTIFIER); // consume ident
        String name = identToken.value();
        
        if (isKnownFunction(name)) {
          consumeExpected(TokenType.LPAREN); // known functions must have parentheses, e.g. sin(x)
          Expr arg = parseExpr(); // parse the argument of the expression
          consumeExpected(TokenType.RPAREN);
          yield new UnaryExpr(resolveFunction(name), arg);
        }

        yield switch (name) {
          case "pi" -> new NumberExpr(Math.PI);
          case "e" -> new NumberExpr(Math.E);
          default -> parseImplicitMul(name);
        };
      }
      case LPAREN -> {
        consumeExpected(TokenType.LPAREN); // consume "("
        Expr expr = parseExpr(); // parse the inner expression
        consumeExpected(TokenType.RPAREN); // consume ")"
        yield expr;
      }
      default -> throw new IllegalArgumentException("Unexpected token: " + token);
    };
  }

  /**
   * Parses implicit multiplication in idents. E.g. "ax" is parsed as "a * x".
   * @param name
   * @return Expr: the new expression formed. E.g. "ax" would return "a * x" as a BinaryExpr.
   */
  private Expr parseImplicitMul(String name) {
    // Handle implicit multiplication, e.g. ax is parsed as a * x 
    if (name.length() == 1) {
      // single treated as single
      return new VariableExpr(name);
    }

    Expr result = new VariableExpr(String.valueOf(name.charAt(0))); // first one
    for (int i = 1; i < name.length(); i++) {
      result = new BinaryExpr(BinaryOp.MUL, result, new VariableExpr(String.valueOf(name.charAt(i))));
    }
    return result;
  }

  /**
   * Checks if the given name is a known function.
   * <p>
   * Known functions list:
   * - sin
   * - cos
   * - tan
   * - exp
   * - ln
   * </p>
   * @param name
   * @return boolean: whether the name is a known function or not.
   */
  private boolean isKnownFunction(String name) {
    return switch (name) {
      case "sin", "cos", "tan", "exp", "ln" -> true;
      default -> false;
    };
  }

  /**
   * Resolves a function name to its corresponding unary operator.
   * <p>
   * Known functions list:
   * - sin
   * - cos
   * - tan
   * - exp
   * - ln
   * </p>
   * @param name
   * @return UnaryOp: the corresponding unary operator for the function name.
   */
  private UnaryOp resolveFunction(String name) {
    return switch (name) {
      case "sin" -> UnaryOp.SIN;
      case "cos" -> UnaryOp.COS;
      case "tan" -> UnaryOp.TAN;
      case "exp" -> UnaryOp.EXP;
      case "ln" -> UnaryOp.LN;
      default -> throw new IllegalArgumentException("Unknown function: " + name);
    };
  }
  
  /**
   * Peeks at current token.
   * <p> Does not consume the current token.
   * </p>
   * @return Token: the current token.
   */
  private Token peek() {
    return tokens.get(pos);
  }
  
  /**
  * Returns and consumes the current token.
  * @return Token: the current token and then consumes by moving forward position.
  */
  private Token consume() {
    return tokens.get(pos++);
  }
  
  /**
   * Consumes if the expected type matches, otherwise throws an error.
   * @param type
   * @return Token: the current token.
   * @throws IllegalArgumentException if the expected type does not match the current token type.
   */
  private Token consumeExpected(TokenType type) {
    Token token = peek();
    if (token.type() != type) {
      throw new IllegalArgumentException("Expected token of type " + type + " but got " + token.type());
    }
    return consume();
  }
}
